# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reactdemofrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://demofrontend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c05be7ad217c40168ff88502a091460b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_45c09374fb164c00b26a477b987e7605 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: demofrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c05be7ad217c40168ff88502a091460b }}/demofrontendimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reactdemofrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e438be7fbbb4790b4f1e38fb29e3bb7 }}
        images: 'demofrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c05be7ad217c40168ff88502a091460b }}/demofrontendimage:${{ github.sha }}'